"""Titles, description and tags.

Two rules shape this module and both are policy, not taste. A title must describe what the
video actually contains - YouTube treats a mismatch between title/thumbnail and content as
misleading metadata, and it is also the fastest way to train the algorithm that your
audience bounces. And the description must disclose that the content is synthetic, because
this channel's whole output is machine-generated.

Titles are generated by the LLM and then scored here, in code. Asking a model to score its
own titles produces confident nonsense; a deterministic scorer at least fails predictably.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from ..core.db import jdump, tx
from ..core.logging import get_logger
from ..llm.base import parse_model
from ..story.prompts import block, sha, system_prompt
from ..story.schema import MetadataDraft

log = get_logger("metadata")

MAX_TITLE = 100          # YouTube hard limit
GOOD_TITLE = (34, 62)    # readable on mobile without truncation
MAX_DESCRIPTION = 4900
MAX_TAGS_CHARS = 460     # YouTube counts total characters across all tags (limit ~500)

# Hashtag limits are not style preferences and getting them wrong is silently expensive.
# YouTube renders only the FIRST THREE hashtags found in the description, above the video
# title - so ordering decides which three do the work. And a description carrying more
# than fifteen makes YouTube ignore *every* hashtag on the video rather than trimming to
# the first fifteen, which is why MAX_HASHTAGS is a hard cap and not a target.
MAX_HASHTAGS = 15
DISPLAY_HASHTAGS = 3
MIN_HASHTAG_LEN = 3
MAX_HASHTAG_LEN = 30

BAIT = re.compile(
    r"\b(you won'?t believe|shocking|gone wrong|must watch|number \d+ will|"
    r"insane|literally|this is why|doctors hate|life.?chang(ing|ed))\b", re.I)


@dataclass
class Metadata:
    title: str
    description: str
    tags: list[str]
    candidates: list[tuple[str, float, dict]]
    model_id: str
    hashtags: list[str] = field(default_factory=list)


def metadata_prompt(story: dict, moral: str, cast: list[dict], minutes: float,
                    channel: str) -> str:
    names = ", ".join(f"{c['name']} the {c['species']}" for c in cast)
    return f"""Write publishing metadata for this finished animated short.

CHANNEL: {channel}
TITLE (working): {story['title']}
LOGLINE: {story['logline']}
HOOK: {story['hook']}
MORAL: {moral}
CAST: {names}
RUNTIME: about {minutes:.0f} minutes

Rules that are not negotiable:
- Every title must describe what genuinely happens in THIS video. No clickbait, no
  promises the video does not keep, no ALL-CAPS shouting, no "you won't believe".
- Titles are 30-65 characters. Front-load the interesting noun.
- The description opens with two sentences that would make someone watch, then a short
  plain summary, then nothing else - the pipeline appends its own credits and disclosures.
- Tags are lowercase, specific, and describe content, not aspiration. No competitor
  channel names, no unrelated trending terms, no misleading tags.
- Hashtags describe THIS story: its animals, its setting, its situation. Give 6-10, single
  words or CamelCase ("RiverRescue", not "river rescue"), no punctuation, no spaces. The
  pipeline adds the channel's own recurring hashtags, so do not invent branding. A hashtag
  that does not match the video is a spam-policy problem, not a growth tactic.

Return JSON:
{{"titles": [{{"title": str, "scores": {{"clarity": 0-1, "curiosity": 0-1,
   "accuracy": 0-1}}, "accuracy_justification": str}}],
  "description": str, "tags": [str], "hashtags": [str]}}

Give 6 title candidates."""


def score_title(title: str, story: dict) -> dict:
    """Deterministic, explainable, and biased toward honesty over heat."""
    t = title.strip()
    n = len(t)
    length = 1.0 if GOOD_TITLE[0] <= n <= GOOD_TITLE[1] else max(
        0.0, 1.0 - abs(n - sum(GOOD_TITLE) / 2) / 45.0)

    shouty = sum(1 for w in t.split() if len(w) > 2 and w.isupper())
    bait = 1.0 if BAIT.search(t) else 0.0
    punct = t.count("!") + t.count("?")

    # Overlap with the story's own words is a cheap proxy for "the title is about the
    # video". It is crude, but it reliably catches a title invented from nothing.
    story_words = set(re.findall(r"[a-z]{4,}", " ".join(
        str(story.get(k, "")) for k in ("title", "logline", "hook", "setting", "moral")
    ).lower()))
    title_words = set(re.findall(r"[a-z]{4,}", t.lower()))
    overlap = len(title_words & story_words) / max(1, len(title_words))

    return {
        "length": round(length, 3),
        "honesty": round(max(0.0, 1.0 - bait - 0.30 * shouty - 0.12 * max(0, punct - 1)), 3),
        "relevance": round(min(1.0, overlap * 1.6), 3),
        "specificity": round(min(1.0, len([w for w in title_words if len(w) > 5]) / 3.0), 3),
    }


def normalise_hashtag(raw: str) -> str:
    """One hashtag, or "" if the input cannot become a usable one.

    A hashtag terminates at the first whitespace, so "#river rescue" tags "river" and
    leaves "rescue" as loose text in the description. Multi-word input is therefore joined
    into CamelCase rather than truncated - dropping the tail silently changes what the
    video is filed under.
    """
    cleaned = re.sub(r"[^0-9A-Za-z ]+", " ", str(raw).replace("#", " "))
    words = cleaned.split()
    if not words:
        return ""
    tag = words[0] if len(words) == 1 else "".join(w[:1].upper() + w[1:] for w in words)
    if len(tag) < MIN_HASHTAG_LEN or tag.isdigit():
        return ""
    return tag[:MAX_HASHTAG_LEN]


def clean_hashtags(*groups: list[str]) -> list[str]:
    """Normalise, dedupe and cap hashtags across ordered groups.

    Groups are consumed in order and the caller passes the most valuable first, because
    only the leading DISPLAY_HASHTAGS are rendered above the title. Deduplication is
    case-insensitive so a channel's "#Animation" is not shipped alongside a model's
    "#animation", which would burn two of the fifteen slots on one tag.
    """
    seen: set[str] = set()
    out: list[str] = []
    for group in groups:
        for raw in group or []:
            tag = normalise_hashtag(raw)
            if not tag or tag.lower() in seen:
                continue
            seen.add(tag.lower())
            out.append(tag)
            if len(out) >= MAX_HASHTAGS:
                return out
    return out


def build_description(story: dict, base: str, cast: list[dict], channel: str,
                      attribution: str, disclose_synthetic: bool,
                      hashtags: list[str], cta: str = "") -> str:
    parts = [base.strip()]
    names = ", ".join(f"{c['name']} the {c['species']}" for c in cast)
    if names:
        parts.append(f"Featuring {names}.")
    if disclose_synthetic:
        # Over-disclose deliberately. YouTube requires altered/synthetic disclosure for
        # realistic content; this is stylised animation, but saying so plainly costs
        # nothing and removes any question of concealment.
        parts.append(
            "About this video: this is an original animated short. The story, artwork, "
            "character animation and voices were produced with AI-assisted tools and "
            "reviewed before publishing. All characters and events are fictional.")
    if attribution.strip():
        parts.append("Credits and licences:\n" + attribution.strip())
    if cta.strip():
        parts.append(cta.strip())
    parts.append(f"— {channel}")
    body = "\n\n".join(p for p in parts if p.strip())
    if not hashtags:
        return body[:MAX_DESCRIPTION]
    line = " ".join(f"#{h}" for h in hashtags)
    # The hashtag line goes last but must survive truncation. A long licence attribution
    # block would otherwise push it past MAX_DESCRIPTION and cost the video its whole
    # discovery surface without anything in the logs saying so.
    room = MAX_DESCRIPTION - len(line) - 2
    if room <= 0:
        return line[:MAX_DESCRIPTION]
    return body[:room].rstrip() + "\n\n" + line


def part_description(base: str, part: int, total: int,
                     earlier_video_ids: list[str] | None = None) -> str:
    """Prefix a part's description with where it sits in the series.

    The pointer goes at the TOP, above the story summary. YouTube collapses a description
    after roughly three lines, so anything below that is invisible unless the viewer taps
    "more" - and a viewer who does not know they are on part 2 of 3 has no reason to tap.
    Links to earlier parts follow, because the person most likely to read this is someone
    who landed on part 3 first and needs a way back to the start.
    """
    if total <= 1:
        return base[:MAX_DESCRIPTION]
    header = [f"Part {part} of {total}."]
    ids = [v for v in (earlier_video_ids or []) if v]
    if ids:
        header.append("Start from the beginning: "
                      + " ".join(f"https://youtu.be/{v}" for v in ids[:3]))
    elif part < total:
        header.append("The next part follows on this channel - subscribe to catch it.")
    out = "\n".join(header) + "\n\n" + base
    return out[:MAX_DESCRIPTION]


def clean_tags(tags: list[str]) -> list[str]:
    seen, out, total = set(), [], 0
    for raw in tags:
        t = re.sub(r"[^a-z0-9 \-]", "", raw.lower()).strip()
        if len(t) < 3 or t in seen:
            continue
        if total + len(t) + 1 > MAX_TAGS_CHARS:
            break
        seen.add(t)
        out.append(t)
        total += len(t) + 1
    return out[:30]


def generate(chain, db: Path, job_id: int, story: dict, cast: list[dict], minutes: float,
             channel: str, attribution: str, disclose_synthetic: bool = True,
             lead_hashtags: list[str] | None = None,
             evergreen_hashtags: list[str] | None = None, cta: str = "") -> Metadata:
    user = metadata_prompt(story, story.get("moral", ""), cast, minutes, channel)
    c = chain.complete(system_prompt(block("channel_bible")), user, role="cheap",
                       max_tokens=2048, temperature=0.85, structured=True)
    draft = parse_model(c.text, MetadataDraft)

    scored: list[tuple[str, float, dict]] = []
    for cand in draft.titles:
        title = cand.title.strip()[:MAX_TITLE]
        s = score_title(title, story)
        # Honesty is a gate, not a weight: a title that trips the bait filter cannot win
        # however well it scores elsewhere.
        total = 0.0 if s["honesty"] < 0.5 else round(
            0.30 * s["length"] + 0.30 * s["relevance"] + 0.22 * s["specificity"]
            + 0.18 * s["honesty"], 4)
        scored.append((title, total, s))
    scored.sort(key=lambda x: -x[1])
    if not scored or scored[0][1] == 0.0:
        # Every candidate failed the gate. The story's own title was written under the
        # same rules and is always safe, so fall back rather than ship bait.
        fallback = story["title"][:MAX_TITLE]
        scored.insert(0, (fallback, 0.5, score_title(fallback, story)))
        log.warning("all_titles_failed_gate_using_story_title", job=job_id)

    tags = clean_tags(draft.tags)
    # Order is the whole design. `lead` first because those are the three YouTube shows
    # above the title, then this story's own hashtags, then the channel's evergreen set to
    # keep every upload in one discoverable cluster. `tags` is a backstop: a model that
    # returned no hashtags at all should still ship a video that is findable.
    hashtags = clean_hashtags(lead_hashtags or [], draft.hashtags,
                              evergreen_hashtags or [], tags)
    description = build_description(story, draft.description, cast, channel, attribution,
                                    disclose_synthetic, hashtags, cta)

    with tx(db) as con:
        con.execute("DELETE FROM metadata_candidates WHERE job_id = ? AND kind = 'title'",
                    (job_id,))
        con.executemany("""
            INSERT INTO metadata_candidates (job_id, kind, value, score, scores, accurate,
                                             chosen)
            VALUES (?,'title',?,?,?,?,?)
        """, [(job_id, t, sc, jdump(det), 1 if det["honesty"] >= 0.5 else 0,
               1 if i == 0 else 0) for i, (t, sc, det) in enumerate(scored)])

    log.info("metadata_built", job=job_id, title=scored[0][0], tags=len(tags),
             hashtags=len(hashtags), shown=hashtags[:DISPLAY_HASHTAGS],
             model=c.model_id)
    return Metadata(title=scored[0][0], description=description, tags=tags,
                    candidates=scored, model_id=c.model_id, hashtags=hashtags)
